// Package policy translates AegisPolicy CRD specs into the Aegis INI policy
// format consumed by the C++ daemon.
package policy

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	v1alpha1 "github.com/ErenAri/aegis-operator/api/v1alpha1"
)

// TranslateResult holds the generated INI policy and its content hash.
type TranslateResult struct {
	INI    string
	SHA256 string

	// AllowOverrides maps a daemon deny section name (e.g. "deny_port") to
	// the canonical rule literals that an `action: Allow` rule in this spec
	// exempts.
	//
	// These are deliberately NOT rendered into INI. The daemon has no
	// [allow_path], [allow_ip], [allow_cidr], [allow_port] or
	// [allow_ip_port] section — src/policy_parse.cpp rejects each as an
	// unknown section, and an unknown section fails the whole file, so a
	// policy that emitted them never applied at all. Allow is therefore
	// resolved operator-side: MergePolicies subtracts these literals from
	// the matching deny sections, which is exactly the Allow > Block
	// precedence documented in docs/POLICY_SEMANTICS.md.
	//
	// [allow_binary_hash] is the one allow section the daemon does
	// implement, so it stays an INI section and is swept via
	// allowOverrideMap instead.
	AllowOverrides map[string][]string
}

// addOverride records an Allow literal against the deny section it exempts.
func (r *TranslateResult) addOverride(denySection, literal string) {
	if r.AllowOverrides == nil {
		r.AllowOverrides = make(map[string][]string)
	}
	r.AllowOverrides[denySection] = append(r.AllowOverrides[denySection], literal)
}

// allowOverrideMap maps an INI Allow section to the Deny section it
// overrides during a merge. Only sections the daemon actually implements
// appear here.
//
// [allow_binary_hash] is the sole allow section in the daemon's
// valid_sections list (src/policy_parse.cpp). Allow for path, ip, cidr,
// port and ip_port rules has no daemon section at all and is carried in
// TranslateResult.AllowOverrides instead — see the field's doc comment.
var allowOverrideMap = map[string]string{
	"[allow_binary_hash]": "[deny_binary_hash]",
}

// TranslateToINI converts an AegisPolicySpec into the Aegis INI policy format.
// The INI format is consumed by the C++ daemon's policy_parse.cpp.
//
// Per-rule Action (Allow/Block, default Block) decides how each rule is
// lowered. Block rules go into `[deny_*]` sections. Allow rules for path,
// ip, cidr, port and ip:port have no daemon section at all, so they are
// recorded in TranslateResult.AllowOverrides and resolved by MergePolicies
// rather than emitted — see that field's doc comment.
//
// Every rule literal is rendered by the canonical formatters in grammar.go,
// which are the single source of truth for the textual grammar shared with
// src/policy_parse.cpp. operator/internal/policy/contract_test.go feeds the
// output of this function to the real daemon parser on every CI run.
func TranslateToINI(spec v1alpha1.AegisPolicySpec) (TranslateResult, error) {
	var b strings.Builder
	var result TranslateResult

	b.WriteString("version=5\n")
	b.WriteString(fmt.Sprintf("# mode=%s\n", spec.Mode))
	b.WriteString("# Generated by aegis-operator from AegisPolicy CRD\n\n")

	buildFileSections(&b, spec.FileRules, &result)
	if err := buildNetworkSections(&b, spec.NetworkRules, &result); err != nil {
		return TranslateResult{}, err
	}
	buildExecSections(&b, spec.ExecRules)
	buildKernelSections(&b, spec.KernelRules)

	content := b.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	result.INI = content
	result.SHA256 = hash
	return result, nil
}

// emitSection writes a non-empty `[name]\nentry\n...` block, sorting and
// de-duplicating entries so the output is deterministic across reconciles.
func emitSection(b *strings.Builder, name string, entries []string) {
	if len(entries) == 0 {
		return
	}
	seen := make(map[string]struct{}, len(entries))
	deduped := make([]string, 0, len(entries))
	for _, e := range entries {
		if _, ok := seen[e]; ok {
			continue
		}
		seen[e] = struct{}{}
		deduped = append(deduped, e)
	}
	sort.Strings(deduped)
	b.WriteString("[" + name + "]\n")
	for _, e := range deduped {
		b.WriteString(e + "\n")
	}
	b.WriteString("\n")
}

// isAllow reports whether a rule action is Allow. An empty action defaults
// to Block, so we only check for the explicit Allow value.
func isAllow(a v1alpha1.RuleAction) bool { return a == v1alpha1.RuleActionAllow }

func buildFileSections(b *strings.Builder, fr *v1alpha1.FileRules, result *TranslateResult) {
	if fr == nil {
		return
	}

	var denyPaths, denyInodes []string
	for _, r := range fr.Deny {
		if isAllow(r.Action) {
			// Inode-based Allow is not a daemon concept; webhook rejects
			// the combination, but defensively skip it here too.
			if r.Path != "" {
				result.addOverride("deny_path", r.Path)
			}
			continue
		}
		if r.Path != "" {
			denyPaths = append(denyPaths, r.Path)
		}
		if r.Inode != "" {
			denyInodes = append(denyInodes, r.Inode)
		}
	}

	var protectPaths []string
	for _, r := range fr.Protect {
		if r.Path != "" {
			protectPaths = append(protectPaths, r.Path)
		}
	}

	emitSection(b, "deny_path", denyPaths)
	emitSection(b, "deny_inode", denyInodes)
	emitSection(b, "protect_path", protectPaths)
}

// buildNetworkSections lowers NetworkRules onto the daemon's network deny
// sections, rendering every rule with the canonical grammar in grammar.go.
//
// Allow rules do not produce INI: the daemon has no [allow_ip]/[allow_cidr]/
// [allow_port]/[allow_ip_port] sections. They are recorded as overrides and
// applied by MergePolicies.
//
// An unrecognised protocol or direction is a hard translation error rather
// than a silently dropped or mis-rendered rule: dropping a Block rule would
// open a hole, and the controller surfaces the error as a Translation
// failure on the policy's status.
func buildNetworkSections(b *strings.Builder, nr *v1alpha1.NetworkRules, result *TranslateResult) error {
	if nr == nil || len(nr.Deny) == 0 {
		return nil
	}

	var denyIPs, denyCIDRs, denyPorts, denyIPPorts []string

	for i, rule := range nr.Deny {
		var section, literal string

		switch {
		case rule.IP != "" && rule.Port > 0:
			l, err := CanonicalIPPortRule(rule.IP, rule.Port, rule.Protocol)
			if err != nil {
				return fmt.Errorf("networkRules.deny[%d]: %w", i, err)
			}
			section, literal = "deny_ip_port", l
		case rule.IP != "":
			section, literal = "deny_ip", rule.IP
		case rule.CIDR != "":
			section, literal = "deny_cidr", rule.CIDR
		case rule.Port > 0:
			l, err := CanonicalPortRule(rule.Port, rule.Protocol, rule.Direction)
			if err != nil {
				return fmt.Errorf("networkRules.deny[%d]: %w", i, err)
			}
			section, literal = "deny_port", l
		default:
			// No recognisable target; nothing to lower.
			continue
		}

		if isAllow(rule.Action) {
			result.addOverride(section, literal)
			continue
		}

		switch section {
		case "deny_ip":
			denyIPs = append(denyIPs, literal)
		case "deny_cidr":
			denyCIDRs = append(denyCIDRs, literal)
		case "deny_port":
			denyPorts = append(denyPorts, literal)
		case "deny_ip_port":
			denyIPPorts = append(denyIPPorts, literal)
		}
	}

	emitSection(b, "deny_ip", denyIPs)
	emitSection(b, "deny_cidr", denyCIDRs)
	emitSection(b, "deny_port", denyPorts)
	emitSection(b, "deny_ip_port", denyIPPorts)
	return nil
}

func buildExecSections(b *strings.Builder, er *v1alpha1.ExecRules) {
	if er == nil {
		return
	}
	if len(er.AllowBinaryHashes) > 0 {
		entries := make([]string, 0, len(er.AllowBinaryHashes))
		for _, h := range er.AllowBinaryHashes {
			entries = append(entries, "sha256:"+h)
		}
		emitSection(b, "allow_binary_hash", entries)
	}
	if len(er.DenyBinaryHashes) > 0 {
		entries := make([]string, 0, len(er.DenyBinaryHashes))
		for _, h := range er.DenyBinaryHashes {
			entries = append(entries, "sha256:"+h)
		}
		emitSection(b, "deny_binary_hash", entries)
	}
	if len(er.DenyComm) > 0 {
		emitSection(b, "deny_comm", er.DenyComm)
	}
}

func buildKernelSections(b *strings.Builder, kr *v1alpha1.KernelRules) {
	if kr == nil {
		return
	}
	if kr.BlockPtrace {
		emitSection(b, "deny_ptrace", []string{"*"})
	}
	if kr.BlockModuleLoad {
		emitSection(b, "deny_module_load", []string{"*"})
	}
	if kr.BlockBpfSyscall {
		emitSection(b, "deny_bpf", []string{"*"})
	}
}

// MergePolicies combines multiple translated policies into a single INI.
// Sections are unioned and entries within each section are de-duplicated.
//
// Allow > Block precedence: any literal that appears in an `[allow_*]`
// section is removed from the matching `[deny_*]` section. This is the
// same conflict-resolution rule used by Tetragon and KubeArmor and is
// documented in docs/POLICY_SEMANTICS.md.
func MergePolicies(policies []TranslateResult) TranslateResult {
	sections := make(map[string][]string)
	for _, p := range policies {
		currentSection := ""
		for _, line := range strings.Split(p.INI, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "version=") {
				continue
			}
			if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
				currentSection = line
				continue
			}
			if currentSection != "" {
				sections[currentSection] = appendUnique(sections[currentSection], line)
			}
		}
	}

	// Collect the structured Allow overrides that never appear as INI
	// sections, keyed the same way as allowOverrideMap so both kinds are
	// applied by one sweep below.
	overrides := make(map[string][]string)
	for _, p := range policies {
		for denySection, literals := range p.AllowOverrides {
			key := "[" + denySection + "]"
			for _, l := range literals {
				overrides[key] = appendUnique(overrides[key], l)
			}
		}
	}
	for allowSection, denySection := range allowOverrideMap {
		for _, l := range sections[allowSection] {
			overrides[denySection] = appendUnique(overrides[denySection], l)
		}
	}

	// Apply Allow > Block precedence: remove any deny entry whose literal
	// is exempted by an Allow rule in any contributing policy.
	for denySection, allowed := range overrides {
		if len(allowed) == 0 {
			continue
		}
		denied := sections[denySection]
		if len(denied) == 0 {
			continue
		}
		allowedSet := make(map[string]struct{}, len(allowed))
		for _, e := range allowed {
			allowedSet[e] = struct{}{}
		}
		kept := make([]string, 0, len(denied))
		for _, e := range denied {
			if _, blocked := allowedSet[e]; blocked {
				continue
			}
			kept = append(kept, e)
		}
		sections[denySection] = kept
	}

	// Sort section names and entries within each section so the merged
	// INI is byte-stable across reconciles.
	sortedSections := make([]string, 0, len(sections))
	for section := range sections {
		sortedSections = append(sortedSections, section)
	}
	sort.Strings(sortedSections)

	var combined strings.Builder
	combined.WriteString("version=5\n")
	combined.WriteString("# Merged policy generated by aegis-operator\n\n")

	for _, section := range sortedSections {
		entries := sections[section]
		if len(entries) == 0 {
			// Section was emptied by the Allow override sweep — drop it.
			continue
		}
		sort.Strings(entries)
		combined.WriteString(section + "\n")
		for _, entry := range entries {
			combined.WriteString(entry + "\n")
		}
		combined.WriteString("\n")
	}

	content := combined.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	return TranslateResult{INI: content, SHA256: hash}
}

func appendUnique(slice []string, item string) []string {
	for _, s := range slice {
		if s == item {
			return slice
		}
	}
	return append(slice, item)
}
