// Package policy — aegis-next policy translator.
//
// TranslateToAegisNext converts an AegisPolicySpec into the aegis-next
// line-based policy format:
//
//	<hook> <match_type> <value> <action> [kill]
//
// This translator is used when the operator detects that the target node
// runs aegisbpf-next instead of the mainline aegisbpf daemon.
package policy

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	v1alpha1 "github.com/ErenAri/aegis-operator/api/v1alpha1"
)

// TranslateToAegisNext converts an AegisPolicySpec into aegis-next's
// line-based policy format. Returns the policy content and its SHA-256 hash.
func TranslateToAegisNext(spec v1alpha1.AegisPolicySpec) (TranslateResult, error) {
	var b strings.Builder

	b.WriteString("# Generated by aegis-operator from AegisPolicy CRD\n")
	b.WriteString(fmt.Sprintf("# mode=%s\n\n", spec.Mode))

	action := "deny"
	if spec.Mode == "audit" {
		action = "log"
	}

	buildNextFileRules(&b, spec.FileRules, action)
	buildNextNetworkRules(&b, spec.NetworkRules, action)
	buildNextExecRules(&b, spec.ExecRules, action)
	buildNextKernelRules(&b, spec.KernelRules, action)

	content := b.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	return TranslateResult{INI: content, SHA256: hash}, nil
}

func buildNextFileRules(b *strings.Builder, fr *v1alpha1.FileRules, defaultAction string) {
	if fr == nil {
		return
	}

	for _, r := range fr.Deny {
		act := defaultAction
		if isAllow(r.Action) {
			act = "allow"
		}
		if r.Path != "" {
			fmt.Fprintf(b, "file  path  %s  %s\n", r.Path, act)
			// Also add fperm rule for path monitoring.
			fmt.Fprintf(b, "fperm  path  %s  %s\n", r.Path, act)
		}
	}

	// Protect rules are always logged.
	for _, r := range fr.Protect {
		if r.Path != "" {
			fmt.Fprintf(b, "fperm  path  %s  log\n", r.Path)
		}
	}

	if len(fr.Deny) > 0 || len(fr.Protect) > 0 {
		b.WriteString("\n")
	}
}

func buildNextNetworkRules(b *strings.Builder, nr *v1alpha1.NetworkRules, defaultAction string) {
	if nr == nil || len(nr.Deny) == 0 {
		return
	}

	for _, r := range nr.Deny {
		act := defaultAction
		killFlag := ""
		if isAllow(r.Action) {
			act = "allow"
		} else if act == "deny" {
			killFlag = "  kill"
		}

		if r.Port > 0 {
			dir := r.Direction
			if dir == "" {
				dir = "outbound"
			}
			// Map direction to hook.
			hook := "conn"
			switch dir {
			case "inbound":
				hook = "bind"
			case "outbound":
				hook = "conn"
			}
			fmt.Fprintf(b, "%s  port  %d  %s%s\n", hook, r.Port, act, killFlag)

			// Also add listen rule for inbound.
			if dir == "inbound" {
				fmt.Fprintf(b, "listen  port  %d  %s%s\n", r.Port, act, killFlag)
			}
		}
	}
	b.WriteString("\n")
}

func buildNextExecRules(b *strings.Builder, er *v1alpha1.ExecRules, defaultAction string) {
	if er == nil {
		return
	}

	// DenyComm → exec comm rules.
	for _, comm := range er.DenyComm {
		fmt.Fprintf(b, "exec  comm  %s  %s  kill\n", comm, defaultAction)
	}

	if len(er.DenyComm) > 0 {
		b.WriteString("\n")
	}
}

func buildNextKernelRules(b *strings.Builder, kr *v1alpha1.KernelRules, defaultAction string) {
	if kr == nil {
		return
	}

	act := defaultAction

	if kr.BlockModuleLoad {
		// Wildcard module load deny — use a known comm placeholder.
		// aegis-next's kmod hook fires on any module request; the policy
		// match is by comm, so we use "*" which FNV-1a hashes to a
		// sentinel. In practice the BPF side denies all kmod requests
		// when this rule is present.
		fmt.Fprintf(b, "kmod  comm  insmod  %s  kill\n", act)
		fmt.Fprintf(b, "kmod  comm  modprobe  %s  kill\n", act)
		fmt.Fprintf(b, "kmod  comm  rmmod  %s\n", act)
	}

	if kr.BlockPtrace {
		fmt.Fprintf(b, "ptrace  comm  gdb  %s  kill\n", act)
		fmt.Fprintf(b, "ptrace  comm  strace  %s  kill\n", act)
		fmt.Fprintf(b, "ptrace  comm  ltrace  %s  kill\n", act)
	}

	if kr.BlockModuleLoad || kr.BlockPtrace {
		b.WriteString("\n")
	}
}

// MergeNextPolicies combines multiple aegis-next translated policies into one.
// Lines are unioned and sorted for deterministic output.
func MergeNextPolicies(policies []TranslateResult) TranslateResult {
	seen := make(map[string]struct{})
	var rules []string

	for _, p := range policies {
		for _, line := range strings.Split(p.INI, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			if _, ok := seen[line]; !ok {
				seen[line] = struct{}{}
				rules = append(rules, line)
			}
		}
	}

	sort.Strings(rules)

	var b strings.Builder
	b.WriteString("# Merged aegis-next policy generated by aegis-operator\n\n")
	for _, r := range rules {
		b.WriteString(r + "\n")
	}

	content := b.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	return TranslateResult{INI: content, SHA256: hash}
}
