# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/aegisbpf-0.1.0-Linux
Summary:        AegisBPF runtime security agent
Name:           aegisbpf
Version:        0.1.0
Release:        1
License:        unknown
Group:          unknown
Vendor:         AegisBPF


Requires: libbpf












Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS

%define _unpackaged_files_terminate_build 0


%global __brp_strip /bin/true
%global __brp_strip_static_archive /bin/true


%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
%dir /etc/aegisbpf
%dir /etc/default
/usr/bin/aegisbpf
%dir /usr/lib/aegisbpf
/usr/lib/aegisbpf/aegis.bpf.o
%dir /usr/lib/systemd
%dir /usr/lib/systemd/system
/usr/lib/systemd/system/aegisbpf.service

%config /etc/default/aegisbpf
%config /etc/aegisbpf/policy.example



%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 0.1.0-1
  Generated by CPack RPM (no Changelog file were provided)


