#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Model-fidelity guard for the formal proofs.
#
# A machine-checked proof is only as trustworthy as the correspondence between
# the model (proofs/inode_alias_resistance.py :: decision()) and the real hook
# bodies it claims to transcribe. Nothing stops a future edit to the hook from
# diverging from the model and leaving the proof green but meaningless.
#
# This guard makes that divergence loud: it extracts the brace-balanced source
# of the modeled functions, hashes it, and compares against a recorded lock. If
# the hook logic changed, the build fails with an instruction to (1) re-verify
# that decision() still mirrors the code and (2) refresh the lock. It is pure
# stdlib (no z3) so it can run as a fast pre-step.

import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LOCK = Path(__file__).resolve().parent / "MODEL_FIDELITY.lock"

# (file, function-signature-anchor) pairs whose bodies the model transcribes.
MODELED = [
    ("bpf/aegis_file.bpf.h", "int BPF_PROG(handle_file_open"),
    ("bpf/aegis_file.bpf.h", "int handle_inode_permission_impl("),
]


def extract_body(text: str, anchor: str) -> str:
    """Return the anchor line plus its brace-balanced body."""
    idx = text.find(anchor)
    if idx == -1:
        raise SystemExit(f"anchor not found: {anchor!r}")
    # find the opening brace at or after the anchor
    brace = text.find("{", idx)
    if brace == -1:
        raise SystemExit(f"no opening brace after anchor: {anchor!r}")
    depth = 0
    i = brace
    while i < len(text):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[idx : i + 1]
        i += 1
    raise SystemExit(f"unbalanced braces for anchor: {anchor!r}")


def normalize(body: str) -> str:
    """Strip comments and collapse whitespace so cosmetic edits don't trip the
    guard but logic edits do."""
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"\s+", " ", body)
    return body.strip()


def current_digest() -> tuple[str, dict]:
    h = hashlib.sha256()
    per = {}
    for rel, anchor in MODELED:
        text = (REPO / rel).read_text()
        norm = normalize(extract_body(text, anchor))
        d = hashlib.sha256(norm.encode()).hexdigest()
        per[f"{rel}::{anchor}"] = d
        h.update(d.encode())
    return h.hexdigest(), per


def main() -> int:
    digest, per = current_digest()
    write = "--update" in sys.argv

    if write:
        lines = ["# Auto-generated by check_model_fidelity.py --update. Do not edit by hand.\n"]
        for k, v in per.items():
            lines.append(f"{v}  {k}\n")
        lines.append(f"{digest}  COMBINED\n")
        LOCK.write_text("".join(lines))
        print(f"lock updated: {LOCK.name} -> {digest[:16]}…")
        return 0

    if not LOCK.exists():
        print(f"FAIL: {LOCK.name} missing. Run: python3 proofs/check_model_fidelity.py --update")
        return 1

    recorded = None
    for line in LOCK.read_text().splitlines():
        if line.strip().endswith("COMBINED"):
            recorded = line.split()[0]
    if recorded == digest:
        print(f"[PASS] model fidelity: hook bodies match lock ({digest[:16]}…)")
        return 0

    print("[FAIL] model fidelity: modeled hook bodies changed since the proof was verified.")
    print(f"       recorded: {recorded}")
    print(f"       current:  {digest}")
    print("       ACTION: confirm proofs/inode_alias_resistance.py :: decision() still")
    print("       mirrors the new hook logic, then run:")
    print("         python3 proofs/check_model_fidelity.py --update")
    return 1


if __name__ == "__main__":
    sys.exit(main())
