#!/usr/bin/env bash
# Regenerate the GitHub Actions workflow inventory + last-run table
# used at the top of `docs/CI_WORKFLOW_AUDIT.md`.
#
# Reads `.github/workflows/*.yml`, queries `gh run list` for the
# most recent run of each workflow, and emits a Markdown table to
# stdout. Pipe to a file or eyeball the diff against the doc.
#
# Requires:
#   - `gh` CLI authenticated against the AegisBPF repo
#     (defaults to the current repo via `gh repo view`).
#   - `awk`, `sed`, `head`.
#
# Usage:
#   scripts/audit_workflows.sh                       # print to stdout
#   scripts/audit_workflows.sh > /tmp/inventory.md   # save
#   scripts/audit_workflows.sh --repo OWNER/REPO     # explicit repo
#
# Re-run periodically (quarterly is enough) and diff the output
# against the table in `docs/CI_WORKFLOW_AUDIT.md` to surface:
#   - newly failing workflows
#   - workflows that have stopped running entirely
#   - workflows that should be promoted from "never run" to active
#
# This script does NOT modify the audit doc. Hand-merge the diff
# so the surrounding prose stays consistent. (A future enhancement
# could add an --update flag that splices the table in place; we
# left that out to keep the script auditable.)

set -euo pipefail

REPO=""
WORKFLOWS_DIR=".github/workflows"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo)
            REPO="$2"
            shift 2
            ;;
        --workflows-dir)
            WORKFLOWS_DIR="$2"
            shift 2
            ;;
        -h | --help)
            sed -n '2,/^set -euo pipefail/p' "$0" | sed 's/^# \{0,1\}//' | head -n -1
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            echo "Try: $0 --help" >&2
            exit 2
            ;;
    esac
done

if ! command -v gh >/dev/null 2>&1; then
    echo "audit_workflows: gh CLI is required" >&2
    exit 2
fi

if [[ -z "${REPO}" ]]; then
    REPO="$(gh repo view --json nameWithOwner --jq '.nameWithOwner' 2>/dev/null || true)"
    if [[ -z "${REPO}" ]]; then
        echo "audit_workflows: --repo not given and gh could not detect the current repo" >&2
        exit 2
    fi
fi

if [[ ! -d "${WORKFLOWS_DIR}" ]]; then
    echo "audit_workflows: ${WORKFLOWS_DIR} not found (run from repo root)" >&2
    exit 2
fi

shopt -s nullglob
workflows=("${WORKFLOWS_DIR}"/*.yml)
shopt -u nullglob

if [[ ${#workflows[@]} -eq 0 ]]; then
    echo "audit_workflows: no workflows found under ${WORKFLOWS_DIR}" >&2
    exit 1
fi

# Trigger summary helper. Emits a comma-separated list of
# top-level GitHub Actions trigger names (push, pull_request,
# schedule, workflow_dispatch, workflow_call, etc.) found in the
# workflow's `on:` block. Filtered against a known-good list so
# nested keys (`inputs:`, `paths:`, `branches:`) don't leak in.
summarize_triggers() {
    local file="$1"
    awk '
        BEGIN {
            triggers["push"]                 = 1
            triggers["pull_request"]         = 1
            triggers["pull_request_target"]  = 1
            triggers["schedule"]             = 1
            triggers["workflow_dispatch"]    = 1
            triggers["workflow_call"]        = 1
            triggers["workflow_run"]         = 1
            triggers["release"]              = 1
            triggers["issues"]               = 1
            triggers["issue_comment"]        = 1
            triggers["create"]               = 1
            triggers["delete"]               = 1
            triggers["fork"]                 = 1
            triggers["label"]                = 1
            triggers["page_build"]           = 1
            triggers["watch"]                = 1
            triggers["repository_dispatch"]  = 1
            triggers["check_run"]            = 1
            triggers["check_suite"]          = 1
            triggers["registry_package"]     = 1
            triggers["status"]               = 1
            triggers["deployment_status"]    = 1
            triggers["branch_protection_rule"] = 1
        }
        # Inline form: `on: push` or `on: [push, pull_request]`.
        /^on:[[:space:]]*[a-zA-Z\[]/ {
            line = $0
            sub(/^on:[[:space:]]*/, "", line)
            gsub(/[\[\]]/, "", line)
            n = split(line, parts, /[ ,]+/)
            for (i = 1; i <= n; ++i) {
                if (parts[i] in triggers) print parts[i]
            }
            next
        }
        /^on:[[:space:]]*$/ { in_on = 1; next }
        in_on && /^[^[:space:]]/ { in_on = 0 }
        in_on && /^[[:space:]]+[a-zA-Z_]+:/ {
            line = $0
            sub(/^[[:space:]]+/, "", line)
            sub(/:.*/, "", line)
            if (line in triggers) print line
        }
    ' "$file" | sort -u | paste -sd ',' - | sed 's/,/, /g'
}

run_count="${#workflows[@]}"

echo "<!-- Generated by scripts/audit_workflows.sh on $(date -u +%Y-%m-%d) against ${REPO} -->"
echo "<!-- ${run_count} workflows under ${WORKFLOWS_DIR}/ -->"
echo
echo "| Workflow | Triggers | Last run | Status |"
echo "|---|---|---|---|"

for wf in "${workflows[@]}"; do
    name="$(basename "${wf}" .yml)"
    triggers="$(summarize_triggers "${wf}")"
    [[ -z "${triggers}" ]] && triggers="—"

    # `gh run list` returns conclusion="" (empty string, not null) for
    # in-progress runs; the // operator only catches null/missing so
    # we explicitly remap empty -> "in_progress".
    line="$(gh run list --workflow="${name}.yml" --repo "${REPO}" --limit 1 \
        --json conclusion,createdAt \
        --jq '.[0] | "\(.createdAt[0:10])|\(if (.conclusion // "") == "" then "in_progress" else .conclusion end)"' \
        2>/dev/null || true)"

    if [[ -z "${line}" || "${line}" == "null" ]]; then
        last_run="—"
        status="never run"
    else
        last_run="${line%%|*}"
        status="${line#*|}"
        case "${status}" in
            success)      status_icon="✅" ;;
            failure)      status_icon="❌" ;;
            cancelled)    status_icon="⚠ cancelled" ;;
            in_progress)  status_icon="⏳" ;;
            skipped)      status_icon="◐ skipped" ;;
            *)            status_icon="${status}" ;;
        esac
        status="${status_icon}"
    fi

    printf "| \`%s\` | %s | %s | %s |\n" "${name}" "${triggers}" "${last_run}" "${status}"
done

echo
echo "<!-- Compare against the inventory in docs/CI_WORKFLOW_AUDIT.md and -->"
echo "<!-- hand-merge changes. See the audit doc's 'Findings' section for -->"
echo "<!-- what each status means and the proposed near-term actions. -->"
