#!/usr/bin/env python3
"""Generate the bpfcompat artifact manifest for aegis.bpf.o from the BPF source.

bpfcompat (https://github.com/ErenAri/adaptive-bpf-runtime-program) validates a
.bpf.o across real kernels in QEMU VMs. It consumes an artifact manifest listing
the programs and their attach points. This script derives that manifest directly
from the `SEC(...)` declarations in bpf/ — the source of truth — so it can never
drift from the actual object.

All programs are marked `required: false`: AegisBPF gates optional programs by
capability at load time, so a missing/unsupported program on an older kernel is
expected, not a failure. The authoritative per-kernel signal is the per-program
`load_status` in each bpfcompat validator-result.json (see the per-program load
probe added to the validator).

Usage: gen_bpfcompat_manifest.py [--out tests/enforcement/bpfcompat-manifest.yaml] [--stdout] [--check]
See docs/KERNEL_COMPAT_MATRIX.md.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BPF_DIR = REPO / "bpf"
OUT = REPO / "tests/enforcement/bpfcompat-manifest.yaml"

SEC_RE = re.compile(r'SEC\("((?:lsm\.s|lsm|tracepoint)/[^"]+)"\)')
# program name on a following line: `int BPF_PROG(name, ...)` or `int name(...)`
NAME_RE = re.compile(r"^\s*int\s+(?:BPF_PROG\(\s*)?([A-Za-z_]\w*)")


def parse_programs() -> list[dict]:
    progs: dict[str, dict] = {}
    for src in sorted(BPF_DIR.glob("*.h")) + sorted(BPF_DIR.glob("*.c")):
        lines = src.read_text(encoding="utf-8").splitlines()
        for i, line in enumerate(lines):
            m = SEC_RE.search(line)
            if not m:
                continue
            section = m.group(1)
            name = None
            for j in range(i + 1, min(i + 4, len(lines))):
                nm = NAME_RE.match(lines[j])
                if nm:
                    name = nm.group(1)
                    break
            if not name:
                continue
            kind = "tracepoint" if section.startswith("tracepoint/") else "lsm"
            attach: dict[str, str | bool] = {"kind": kind}
            if kind == "tracepoint":
                # tracepoint/<category>/<name>
                parts = section.split("/", 2)
                if len(parts) == 3:
                    attach["category"] = parts[1]
                    attach["name"] = parts[2]
            else:
                # lsm/<hook> or lsm.s/<hook>
                attach["name"] = section.split("/", 1)[1]
            attach["required"] = False
            progs[name] = {"name": name, "section": section, "type": kind, "attach": attach}
    return [progs[k] for k in sorted(progs)]


def render(programs: list[dict]) -> str:
    out = [
        "# GENERATED by scripts/gen_bpfcompat_manifest.py from bpf/ SEC() declarations.",
        "# Do not edit by hand. Consumed by the bpfcompat kernel matrix validator.",
        "# All programs are required: false — AegisBPF gates optional programs by",
        "# capability at load; the per-kernel signal is each validator-result.json's",
        "# per-program load_status. See docs/KERNEL_COMPAT_MATRIX.md.",
        "name: aegis-bpf",
        "programs:",
    ]
    for p in programs:
        out.append(f"  - name: {p['name']}")
        out.append(f"    section: {p['section']}")
        out.append(f"    type: {p['type']}")
        out.append("    attach:")
        out.append(f"      kind: {p['attach']['kind']}")
        if "category" in p["attach"]:
            out.append(f"      category: {p['attach']['category']}")
        if "name" in p["attach"]:
            out.append(f"      name: {p['attach']['name']}")
        out.append("      required: false")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the bpfcompat manifest for aegis.bpf.o")
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--check", action="store_true", help="fail if the committed manifest is stale")
    args = ap.parse_args()

    programs = parse_programs()
    if not programs:
        print("error: no programs parsed from bpf/ SEC() declarations", file=sys.stderr)
        return 1
    rendered = render(programs)

    if args.check:
        if not args.out.is_file() or args.out.read_text(encoding="utf-8") != rendered:
            print(f"error: {args.out.name} is stale — run scripts/gen_bpfcompat_manifest.py", file=sys.stderr)
            return 1
        print(f"{args.out.name} up to date ({len(programs)} programs).")
        return 0
    if args.stdout:
        sys.stdout.write(rendered)
    else:
        args.out.write_text(rendered, encoding="utf-8")
        print(f"wrote {args.out.relative_to(REPO)} ({len(programs)} programs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
